language: php

sudo: false

php:
    - 7.0

before_install:
  - composer self-update

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit ./tests/ --bootstrap ./tests/bootstrap.php --color

notifications:
    email: false
